### ISSUE TITLE
Feature Request: stencil overlay

### ISSUE THREAD

**Issue by luka-mikec** [Norserium/vue-advanced-cropper#121]
Could you add a (simple) way to add an overlay for the rectangle stencil? I think a div, sibling to this one, would suffice: https://github.com/Norserium/vue-advanced-cropper/blob/master/src/components/helpers/Preview.vue#L197

It would be ideal if this was implemented as a slot for the main cropper component. 

My use case is that I wish to provide a visual helper to the user (similar to the grid, but more advanced) on how to position the stencil.

**Comment by Norserium** [comment]
@luka-mikec, could you draw / provide the example of what you want to get?

**Comment by luka-mikec** [comment]
@Norserium 

I need something like this displayed above the stencil:
![image](https://user-images.githubusercontent.com/5161084/111508632-33210b80-874c-11eb-99dc-8109c8f9e381.png)

So, it would be a semi-transparent PNG overlaying the stencil. In the meantime I realised I can probably accomplish this by overriding ::before and ::after (initially I thought I can't use them because I thought I'd need to use them for <img>, which doesn't support pseudo-elements), but it would be great if there was an easier way...

**Comment by Norserium** [comment]
You can simplify the code above:
```css
.stencil-preview {
    &:after {
      content: '';
      background-image: url("~@/assets/OVERLAY.png");
      background-size: contain;
      opacity: 1 !important;
      position: absolute;
      pointer-events: none;
      z-index: 1;
      width: 100%;
      height: 100%;
      left: 0;
      top: 0;
    }
}
```

And in the template:
```html
<cropper :stencil-props="{ previewClass: 'stencil-preview' }" />
```

If you need something more complex it's better to create [the custom stencil](https://norserium.github.io/vue-advanced-cropper/guides/advanced-stencil.html).
